theme = "monokai_pro"

[editor]
line-number = "relative"
auto-save = true
bufferline = "multiple"
cursorline = true
idle-timeout = 50
completion-trigger-len = 1

[editor.statusline]
right = ["spinner", "file-encoding", "position", "position-percentage"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "‚ñè"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
C-s = ":w"
0 = "goto_line_start"
"$" = "goto_line_end"
S = [ "extend_to_line_bounds", "trim_selections", "change_selection" ]

[keys.insert]
C-s = ":w"
C-space = "completion"
